version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.9.8
    ports:
      - 5673:5673
    # volumes:
    #   - conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ".env"
    volumes:
      - .:/app
    command: gunicorn --workers 4 --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker main:app
    depends_on:
      - rabbitmq
  worker:
    build: .
    command: ["celery", "-A", "src.tasks", "beat", "-l", "ERROR"]
    env_file:
      - ".env"
    # volumes:
    #   - .:/app
    depends_on:
      - rabbitmq
      - api